### ISSUE TITLE
Status bar text is white vs black on first-time load

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#538] opened 2017-05-17 01:27 UTC
gif
https://d1ax1i5f2y3x71.cloudfront.net/items/0K0g1l2t1s3X0r2C2x2u/Screen%20Recording%202017-05-16%20at%2009.27%20PM.gif?X-CloudApp-Visitor-Id=1563485&v=dcf6f62d

**Comment by alloy** [comment] 2017-05-17 07:18
I’m unable to reproduce this.

@sarahscott @l2succes Can you?

**Comment by l2succes** [comment] 2017-05-17 11:11
@alloy Yeah I'm able to repro on the latest beta build, looking into it

**Comment by mennenia** [comment] 2017-05-17 11:11
Getting this on device - it's there, and then it's gone. 

@l2succes and I are going to have a look now

**Comment by sarahscott** [comment] 2017-05-17 11:17
FWIW I'm not able to repro

**Comment by alloy** [comment] 2017-05-18 09:21
Fixed by https://github.com/artsy/eigen/pull/2348

**Closed by alloy** 2017-05-18 09:21 UTC
