### ISSUE TITLE
[Header] Hide Nationality / birth year line when info isn't present

### ISSUE THREAD

**Issue by briansw** [artsy/emission#96] opened 2016-05-24 13:04 UTC
![screen shot 2016-05-24 at 9 04 22 am](https://cloud.githubusercontent.com/assets/1022172/15504769/8a7a6f4e-218e-11e6-906f-5cbfcd71d463.png)

**Comment by alloy** [comment] 2016-05-24 13:06
Dupe of #86.

**Closed by alloy** 2016-05-24 13:06 UTC
Labels: QA
