### ISSUE TITLE
Switchboard issues showing up on artist VC again

### ISSUE THREAD

**Issue by katarinabatina** [artsy/emission#328] opened 2016-10-03 14:03 UTC
![image](https://cloud.githubusercontent.com/assets/6482926/19040077/9099afc8-8950-11e6-935b-a4850ca87fa8.png)

**Comment by katarinabatina** [comment] 2016-10-03 14:07
(this happens when you come from search) probably a dupe

**Comment by alloy** [comment] 2016-10-12 10:18
Dupe of https://github.com/artsy/eigen/issues/1571

**Closed by alloy** 2016-10-12 10:18 UTC
