### ISSUE TITLE
[Biography] Don't truncate bio / shorten born to b.

### ISSUE THREAD

**Issue by briansw** [artsy/emission#97] opened 2016-05-24 13:06 UTC
- [x] Shorten born to b.
- [x] Don't truncate bioline. let it wrap to next line.

![screen shot 2016-05-24 at 9 06 03 am](https://cloud.githubusercontent.com/assets/1022172/15504817/c35cecb0-218e-11e6-8d21-42a706e5c8c0.png)

**Comment by mennenia** [comment] 2016-05-26 06:13
@sarahscott am I right in assuming you've done the first one in this ticket (which is essentially a dupe of #107) but not the second?

**Comment by alloy** [comment] 2016-05-26 06:41
No #107 is about the header component, this is about the bioline underneath the 'blurb'.

**Comment by mennenia** [comment] 2016-05-26 06:56
:+1: Great. On in, then!

**Closed** 2016-05-26 09:52 UTC
Labels: QA
